from __future__ import annotations

from datetime import datetime, timedelta, timezone

from pmr.models import Market, MarketSeries, MarketSnapshot


def build_sample_market_series() -> tuple[MarketSeries, ...]:
    now = datetime.now(timezone.utc).replace(minute=0, second=0, microsecond=0)
    start = now - timedelta(days=27)

    return (
        MarketSeries(
            market=Market(
                market_id="fed-cut-june-2026",
                question="Will the Fed cut rates by June 2026?",
                category="macro",
                tags=("rates", "fed", "inflation"),
                url="https://example.com/fed-cut-june-2026",
                volume_7d_usd=1_450_000,
                volume_24h_usd=280_000,
                open_interest_usd=410_000,
            ),
            snapshots=_daily_snapshots(
                start,
                [
                    0.26,
                    0.27,
                    0.28,
                    0.27,
                    0.29,
                    0.28,
                    0.27,
                    0.29,
                    0.30,
                    0.31,
                    0.30,
                    0.32,
                    0.31,
                    0.30,
                    0.31,
                    0.33,
                    0.34,
                    0.33,
                    0.34,
                    0.36,
                    0.38,
                    0.41,
                    0.43,
                    0.45,
                    0.46,
                    0.48,
                    0.49,
                    0.47,
                ],
            ),
            research_hints=(
                "Softer inflation data and weaker labor prints would make earlier Fed easing more credible.",
                "Recent Fedspeak turning less hawkish would fit a sustained repricing rather than a one-off spike.",
            ),
        ),
        MarketSeries(
            market=Market(
                market_id="primary-candidate-2028",
                question="Will Candidate X win the 2028 primary?",
                category="politics",
                tags=("elections", "primary"),
                url="https://example.com/primary-candidate-2028",
                volume_7d_usd=820_000,
                volume_24h_usd=175_000,
                open_interest_usd=260_000,
            ),
            snapshots=_daily_snapshots(
                start,
                [
                    0.15,
                    0.16,
                    0.17,
                    0.17,
                    0.18,
                    0.19,
                    0.18,
                    0.20,
                    0.19,
                    0.18,
                    0.19,
                    0.20,
                    0.21,
                    0.20,
                    0.19,
                    0.18,
                    0.20,
                    0.22,
                    0.24,
                    0.26,
                    0.29,
                    0.31,
                    0.33,
                    0.35,
                    0.36,
                    0.38,
                    0.40,
                    0.39,
                ],
            ),
            research_hints=(
                "A strong debate performance or a major endorsement wave would explain a persistent upward move.",
            ),
        ),
        MarketSeries(
            market=Market(
                market_id="regional-offensive-2026",
                question="Will Country A launch a ground offensive in Region B by August 2026?",
                category="geopolitics",
                tags=("conflict", "war", "international"),
                url="https://example.com/regional-offensive-2026",
                volume_7d_usd=1_980_000,
                volume_24h_usd=460_000,
                open_interest_usd=690_000,
            ),
            snapshots=_daily_snapshots(
                start,
                [
                    0.34,
                    0.35,
                    0.34,
                    0.36,
                    0.35,
                    0.34,
                    0.35,
                    0.36,
                    0.37,
                    0.38,
                    0.37,
                    0.36,
                    0.38,
                    0.39,
                    0.38,
                    0.39,
                    0.40,
                    0.41,
                    0.42,
                    0.45,
                    0.49,
                    0.54,
                    0.57,
                    0.60,
                    0.62,
                    0.64,
                    0.63,
                    0.62,
                ],
            ),
            research_hints=(
                "Troop mobilization, reserve call-ups, or evacuation notices often appear on X before they reach mainstream coverage.",
                "Satellite imagery or local OSINT reporting would be high-value evidence for confirming whether this is a real escalation.",
            ),
        ),
        MarketSeries(
            market=Market(
                market_id="nba-finals-2026",
                question="Will Team Y win the 2026 NBA Finals?",
                category="sports",
                tags=("basketball",),
                volume_7d_usd=2_200_000,
                volume_24h_usd=510_000,
                open_interest_usd=730_000,
            ),
            snapshots=_daily_snapshots(
                start,
                [
                    0.41,
                    0.42,
                    0.40,
                    0.41,
                    0.39,
                    0.40,
                    0.41,
                    0.42,
                    0.43,
                    0.41,
                    0.40,
                    0.42,
                    0.43,
                    0.44,
                    0.45,
                    0.46,
                    0.47,
                    0.45,
                    0.44,
                    0.46,
                    0.48,
                    0.50,
                    0.53,
                    0.52,
                    0.54,
                    0.55,
                    0.56,
                    0.55,
                ],
            ),
        ),
        MarketSeries(
            market=Market(
                market_id="illiquid-cabinet-shuffle",
                question="Will Minister Z leave the cabinet this quarter?",
                category="politics",
                tags=("government",),
                volume_7d_usd=7_500,
                volume_24h_usd=900,
                open_interest_usd=2_200,
            ),
            snapshots=_daily_snapshots(
                start,
                [
                    0.09,
                    0.10,
                    0.11,
                    0.09,
                    0.12,
                    0.08,
                    0.11,
                    0.10,
                    0.13,
                    0.12,
                    0.15,
                    0.18,
                    0.17,
                    0.14,
                    0.16,
                    0.19,
                    0.21,
                    0.24,
                    0.28,
                    0.31,
                    0.37,
                    0.42,
                    0.39,
                    0.44,
                    0.41,
                    0.47,
                    0.45,
                    0.43,
                ],
            ),
        ),
    )


def _daily_snapshots(start: datetime, probabilities: list[float]) -> tuple[MarketSnapshot, ...]:
    return tuple(
        MarketSnapshot(observed_at=start + timedelta(days=index), probability=probability)
        for index, probability in enumerate(probabilities)
    )
